baseURL = 'https://Iwert-m.github.io'
languageCode = 'en'
title = 'Iwert'

[markup]
# (Optional) To be able to use all Prism plugins, the theme enables unsafe
# rendering by default
#_merge = "deep"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[build]
# The theme enables writeStats which is required for PurgeCSS
_merge = "deep"

# Tag Cloud
[params.tagCloud]
enable = true
minFontSizeRem = 0.8
maxFontSizeRem = 2.0
# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
[[module.imports]]
path = "github.com/schnerring/hugo-theme-gruvbox"
[[module.imports]]
path = "github.com/schnerring/hugo-mod-json-resume"

[[module.mounts]]
source = "data"
target = "data"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "assets/css/json-resume.css"
target = "assets/css/critical/44-json-resume.css"
[[module.mounts]]
# required by hugo-mod-json-resume
source = "node_modules/simple-icons/icons"
target = "assets/simple-icons"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "node_modules/prismjs"
target = "assets/prismjs"
[[module.mounts]]
source = "node_modules/prism-themes/themes"
target = "assets/prism-themes"
[[module.mounts]]
source = "node_modules/typeface-fira-code/files"
target = "static/fonts"
[[module.mounts]]
source = "node_modules/typeface-roboto-slab/files"
target = "static/fonts"
[[module.mounts]]
source = "node_modules/@tabler/icons/icons"
target = "assets/tabler-icons"

[menus]
[[menus.main]]
name = 'Recent posts'
pageRef = '/posts'
weight = 10
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 10
[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[params.logo]
text = "ITstack"
url = "/"

[params]
[params.prism]
languages = [
  "markup",
  "hcl",
  "go",
  "sql",
  "yaml",
  "git",
  "bash",
  "splunk-spl",
  "powershell",
  "csharp",
]
plugins = [
  "autoloader",
  "normalize-whitespace",
  "toolbar",
  "copy-to-clipboard",
  "command-line",
  "treeview",
  "line-numbers",
]
